<section id="login-container">
    <div class="row">
        <div class="col-xs-offset-1 col-xs-10 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 " id="login-wrapper">
            <?php echo (isset($this->alert) ? $this->alert : ''); ?>
            <div class="panel panel-default animated flipInY">
                <div class="panel-heading text-center">
                    Cadastro de Usuário
                </div>
                <div class="panel-body">
                    <div class="form-group col-md-12 col-xs-12 col-sm-12 col-lg-12">
                        <div class="col-md-4">
                            <div id="errors_campus"></div>
                        </div>
                    </div>

                    <form autocomplete="off" method="post" class="form-horizontal" action="<?=BASE?>cadastro/cadastrousuario/" role="form">

                        <div class="form-group ">
                            <div class="col-md-12">
                                <label class="control-label" for="username">*E-mail:</label>
                                <input type="email" class="form-control" id="id_nome" required="" name="email" value="<?=$view_request['email'];?>" placeholder="E-mail" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6 col-md-6">
                                <label for="id_senha">*Senha:</label>
                                <input type="password" class="form-control" id="id_senha" required="" name="senha" placeholder="Senha" />
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <label for="password">*Confirmar Senha:</label>
                                <input type="password" class="form-control col-md-5" required="" id="confirsenha" placeholder="Senha" />
                            </div>
                            <span class="label label-danger col-md-8 col-md-offset-2" id="erroSenhas" style="display: none;">As senhas não coincidem</span>
                            <span class="label label-warning col-md-8 col-md-offset-2" id="erroSenhasTamanho" style="display: none;">Necessário no minimo 6 caracteres!</span>
                        </div>
                            
                        <p>* Campos Obrigatórios</p>

                        <div class="form-group btnbtn">
                            <button id="btn_cad" class="btn btn-success col-xs-12  col-md-6  pull-right">Cadastrar</button>
                            <input type="button" class="btn btn-danger col-xs-12 col-md-6 pull-left" value="Voltar" onclick="location.href = '<?=BASE?>';">
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>