<?php $data = "";
foreach($view_estados as $val){
	$data .= "<datalist id='".$val->id."'>";
	foreach($val->cidades as $vall){
		$data .= "<option value='".$vall->nome."'>";
	}
	$data .= "</datalist>";
}
echo $data;
?>

<section id="login-container">
    <div class="row">
        <div class="col-xs-offset-1 col-xs-10 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 " id="login-wrapper">
            <?php echo (isset($this->alert) ? $this->alert : ''); ?>
            <div class="panel panel-default animated flipInY">
                <div class="panel-heading text-center">
                    Cadastro
                </div>
                <div class="panel-body">
                    <div class="form-group col-md-12 col-xs-12 col-sm-12 col-lg-12">
                        <div class="col-md-4">
                            <div id="errors_campus"></div>
                        </div>
                    </div>

                    <form autocomplete="off" method="post" class="form-horizontal" action="<?=BASE?>cadastro/cadastrousuario/" role="form">

                        <div class="form-group ">
                            <div class="col-md-12">
                                <label class="control-label" for="username">*Nome:</label>
                                <input type="text" class="form-control" id="id_nome" required="" name="nome" value="<?=$view_request['nome'];?>" placeholder="Nome" />
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-6">
                                <label for="exampleInputEmail1">*Email:</label>
                                <input value="<?=$view_request['email'];?>" type="email" required="" class="form-control" id="id_email" name="email" placeholder="Email" />

                            </div>
                            <div class="col-sm-6 col-md-3">
                                <label for="id_senha">*Senha:</label>
                                <input type="password" class="form-control" id="id_senha" required="" name="senha" placeholder="Senha" />
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <label for="password">*Confirmar Senha:</label>
                                <input type="password" class="form-control col-md-5" required="" id="confirsenha" placeholder="Senha" />
                            </div>
                            <span class="label label-danger col-md-8 col-md-offset-2" id="erroSenhas" style="display: none;">As senha não coicidem!</span>
                            <span class="label label-warning col-md-8 col-md-offset-2" id="erroSenhasTamanho" style="display: none;">Necessário no minimo 6 caracteres!</span>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4 col-md-2">
                                <label>*Estado:</label>
                                <select class="form-control" required="" id="estado_id">
									<option value="" disabled="" selected="">Selecione...</option>
									<?php   foreach($view_estados as $es){ ?>
									<option value="<?=$es->id;?>"><?=$es->sigla;?></option>
									<?php } ?>
								</select>
                            </div>
                            <div class="col-sm-8 col-md-5">
                                <label for="id_cidade">*Cidade:</label>
                                <select id="cidade_id" name="cidade_id" required="" class="form-control"></select>
                            </div>
                            <div class="col-sm-6 col-md-5">
                                <label for="id_telefone">*Telefone:</label>
                                <input value="<?=$view_request['telefone'];?>" required="" type="text" placeholder="(DD)9 9999-9999" class="form-control col-md-5" id="id_telefone" name="telefone" maxlength="11" />

                            </div>
                            <div class="col-sm-6 col-md-3">
                                <label for="password">*CEP:</label>
                                <input value="<?=$view_request['cep'];?>" required="" type="text" class="form-control col-md-5" id="id_cep" name="cep" placeholder="CEP" maxlength="8" />
                            </div>
                            <div class="col-sm-9 col-md-6">
                                <label for="password">*Endereço:</label>
                                <input value="<?=$view_request['endereco'];?>" required="" type="text" class="form-control" id="" name="endereco" placeholder="Endereço" />
                            </div>
                            <div class="col-sm-3 col-md-3">
                                <label for="password">*Número:</label>
                                <input value="<?=$view_request['numero'];?>" required="" type="text" class="form-control" id="id_numero" name="numero" placeholder="Número" maxlength="7" />
                            </div>
                        </div>
                        <p>* Campos Obrigatórios</p>

                        <div class="form-group btnbtn">
                            <button id="btn_cad" class="btn btn-success col-xs-12  col-md-6  pull-right">Cadastrar</button>
                            <input type="button" class="btn btn-danger col-xs-12 col-md-6 pull-left" value="Voltar" onclick="location.href = '<?=BASE?>';">
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>