<div class="col-md-8 col-md-offset-2">
	<?php echo (isset($this->alert) ? $this->alert : '' );?>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h3 class="panel-title">Perfil</h3>
  		</div>
  		<div class="panel-body">
  			<form action="<?=BASE?>home/perfil" method="POST">
    		 <div class="form-group">

				<label for="id_curso">Curso*</label>
			    <input value="<?=$view_request->curso;?>" type="text" class="form-control" id="id_curso" placeholder="Curso" name="curso" required="">

			    <label for="id_serie">Série / Módulo / Período*</label>
			    <input value="<?=$view_request->serie_modulo;?>" type="text" class="form-control" id="id_serie" placeholder="Série / Modulo / Período" name="serie_modulo" required="">
			  </div>
			   <div class="form-group col-md-4 col-md-offset-5">
	            <button class="btn btn-success">Salvar alterações</button>
	          </div>
			  </form>
  		</div>
	</div>
</div>		