<div class="col-md-8 col-md-offset-2">
	<?php (isset($this->alert) ? $this->alert : ''); ?>
	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h3 class="panel-title">Perfil</h3>
  		</div>
  		<div class="panel-body">
  			<form action="<?=BASE?>home/index/perfil" method="POST">
    		 <div class="form-group">
			    <label for="id_razao">Razão Social / Fantasia</label>
			    <input value="<?=$view_request->razao_social;?>" type="text" class="form-control" id="id_razao" placeholder="Razão Social / Fantasia" name="razao_social">
			  </div>
			 	
			</form>
  		</div>
	</div>
</div>		