<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="col-md-offset-4">
				<h3><span class="label label-info">Dados da vaga</span></h3>
			</div>
			<?php echo (isset($this->alert) ? $this->alert : ''); ?>
			<form action="<?=BASE;?>estagio/criar/1" method="POST" role="form">
				<div class="form-group">
					<div class="col-md-4">
						<label class="control-label" for="username">*Cargo:</label>
						<select class="form-control" name="cargo_id" aria-descrubedby="cargo_help">
							<?php   foreach($view_cargos as $es){ ?>
							<option value="<?=$es->id;?>"><?=$es->nome;?></option>
							<?php } ?>
						</select>
						<span id="cargo_help" class="help-block"><a href="" data-toggle="modal" data-target="#cadastrar_cargo">Novo Cargo, clique aqui!</a></span>
					</div>
					<div class="col-md-2">
						<label class="control-label" for="username">*Vagas:</label>
						<input type="number" class="form-control" required="" id="id_qnt" name="qnt" value="<?=$view_request['qnt'];?>" placeholder="Qntd" />
					</div>
					<div class="col-md-4">
						<label class="control-label" for="username">*Remuneração (Se houver):</label>
						<div class="input-group">
							<div class="input-group-addon">R$</div>
							<input type="number" class="form-control" id="id_remuneracao" name="remuneracao" value="<?=$view_request['remuneracao'];?>" placeholder="Remuneração" />
							<div class="input-group-addon">.00</div>
						</div>
					</div>
					<div class="col-md-12">
						<label class="control-label" for="username">*Descrição:</label>
						<textarea class="form-control" id="id_descricao" name="descricao" rows="4"  placeholder="Descrição da Vaga"><?=$view_request['descricao'];?></textarea>
					</div>
					<div class="col-md-4">
						<label class="control-label" for="username">*Duração:</label>
						<div class="input-group">
								<input type="number" class="form-control" id="id_duracao" name="duracao" value="<?=$view_request['duracao'];?>" placeholder="Duração" aria-descrubedby="duracao_help"/>
								<div class="input-group-btn" style="width: 40%;">
								<select name="definicao_tempo" id="" class="form-control">
									<option value="Dias" selected="">Dias</option>
									<option value="Meses">Meses</option>
									<option value="Anos">Anos</option>
								</select>
								</div >
						</div>
						<span id="duracao_help" class="help-block">Ex: 2 meses</span>
					</div>
					<div class="col-md-2">
						<label class="control-label" for="username">*Idade Mínima:</label>
						<input type="text" class="form-control" id="id_idademinima" name="idademinima" value="<?=$view_request['idademinima'];?>"  />
					</div>
					<div class="col-md-2">
						<label class="control-label" for="username">*CH(Semanal)</label>
						<div class="input-group">
							<input type="number" class="form-control" id="id_cargahoraria" name="cargahoraria" value="<?=$view_request['cargahoraria'];?>" />
							<div class="input-group-addon">h</div>
						</div>
						<span id="cargahoraria_help" class="help-block">Ex: 20h</span>
					</div>
					<div class="col-md-3">
						<label class="control-label" for="username">*Requisitos:</label>
						<div id="requist">
						</div>
						<div class="input-group">
							
							<input type="text" class="form-control" id="id_requisitos" placeholder="" />
							<span class="input-group-btn">
								<button class="btn btn-info" type="button"><span class="glyphicon glyphicon-plus-sign"></span></button>
							</span>
						</div>
					</div>
				</div>
				
					<div class="col-md-12 col-md-offset-5">
						<button class="btn btn-success">Cadastrar vaga(s)</button>
					</div>
			</form>
		</div>
	</div>
</div>
<div class="modal fade"  id="cadastrar_cargo" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Novo Cargo</h4>
			</div>
			<div class="modal-body">
				<form class="form-inline" action="<?=BASE;?>estagio/criar/2" method="POST">
					<div class="form-group">
						<label class="control-label" for="username">Nome:</label>
						<input type="text" class="form-control" id="id_cargo" name="nome"/>
					</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
				<button type="submit" class="btn btn-primary">Cadastrar</button>
			</div>
			</form>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
