<script type="text/javascript">
	$(document).ready(function() {
		$("#definicao_tempo").find('option').each(function(index, el) {
			if($(this).val() == '<?=$view_request->definicao_tempo?>'){
				$(this).attr('selected','selected');
			}
		});
	});
</script>
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="col-md-offset-4">
				<h3><span class="label label-info">Alteração de Dados da vaga</span></h3>
			</div>
			<?php echo (isset($this->alert) ? $this->alert : ''); ?>
			<form action="<?=BASE;?>estagio/editarVaga/<?=$view_request->id;?>/alt" method="POST" role="form">
				<div class="form-group">
					<div class="col-md-4">
						<label class="control-label" for="username">*Cargo:</label>
						<select disabled="" class="form-control" name="cargo_id" aria-descrubedby="cargo_help">
									<?php   foreach($view_cargos as $es){ 
										if($es->id == $view_request->cargo_has_instituicao->cargo->id){ ?> 
											<option selected="selected" value="<?=$es->id;?>"><?=$es->nome;?></option> 
									<?php
										}
										else{
										?>
									<option value="<?=$es->id;?>"><?=$es->nome;?></option>
									<?php } } ?>
						</select>
						
					</div>
					<div class="col-md-2">
						<label class="control-label" for="username">*Vagas:</label>
						<input type="number" class="form-control" required="" id="id_qnt" name="qnt" value="<?=$view_request->qnt;?>" placeholder="Qntd" />
					</div>
					<div class="col-md-4">
						<label class="control-label" for="username">*Remuneração (Se houver):</label>
						 <div class="input-group">
      						<div class="input-group-addon">R$</div>
								<input type="number" class="form-control" id="id_remuneracao" name="remuneracao" value="<?=$view_request->remuneracao;?>" placeholder="Remuneração" />
							<div class="input-group-addon">.00</div>
						</div>
					</div>
					<div class="col-md-12">
						<label class="control-label" for="username">*Descrição:</label>
						<textarea class="form-control" id="id_descricao" name="descricao" rows="4"  placeholder="Descrição da Vaga"><?=$view_request->descricao;?></textarea>
					</div>
					<div class="col-md-4">
						<label class="control-label" for="username">*Duração:</label>
						<div class="input-group">
								<input type="number" class="form-control" id="id_duracao" name="duracao" value="<?=$view_request->duracao;?>" placeholder="Duração" aria-descrubedby="duracao_help"/>
								<div class="input-group-btn" style="width: 40%;">
								<select name="definicao_tempo" id="definicao_tempo" class="form-control">
									<option value="Dia(s)" selected="">Dia(s)</option>
									<option value="Mes(es)">Mes(es)</option>
									<option value="Ano(s)">Ano(s)</option>
								</select>
								</div >
						</div>
					</div>
					<div class="col-md-2">
						<label class="control-label" for="username">*Idade Mínima:</label>
						<input type="text" class="form-control" id="id_idademinima" name="idademinima" value="<?=$view_request->idademinima;?>"  />
					</div>
					<div class="col-md-2">
						<label class="control-label" for="username">*CH(Semanal)</label>
						<div class="input-group">
							<input type="text" class="form-control" id="id_cargahoraria" name="cargahoraria" value="<?=$view_request->cargahoraria;?>" />
							<div class="input-group-addon">h</div>
						</div>
						<span id="cargahoraria_help" class="help-block">Ex: 20h</span>
					</div>
					<div class="col-md-4">
						<div id="requist">
							<?php foreach ($view_requisitos as $key => $value) { ?>
							<div class="input-group"><input type="text" name="requisito-<?=$key+1;?>" disabled class="req_sito" value="<?=$value->requisito?>"><span class='glyphicon glyphicon-edit edita_requisito' aria-hidden='true'> </span> <span class="remove_campo"> X</span></div>
							<?php } ?>
						</div>
						<label class="control-label" for="username">*Requisitos:</label>
						<div class="input-group">
							
							<input type="text" class="form-control" id="id_requisitos" placeholder="" />
							<span class="input-group-btn">
								<button class="btn btn-info" type="button"><span class="glyphicon glyphicon-plus-sign"></span></button>
							</span>
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-4 col-md-offset-5">
						<button class="btn btn-success">Salvar alterações</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>