<div id="ret">	</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>
				<span class="label label-info col-md-offset-4">
					Minhas Inscrições

				</span>
			</h1>
		</div>
			<div class="col-md-3 col-md-offset-7" style="margin-top: 2%;">
				<div class="input-group">
					<input type="text" id="busca" class="form-control" placeholder="Buscar...">
					<span class="input-group-btn">
						<button class="btn btn-default" type="button">Buscar</button>
					</span>
				</div><!-- /input-group -->
			</div>
		<div class="col-md-offset-2 col-xs-offset-1 col-md-8 col-xs-10" style="margin-top: 2%;">
			<div class="panel panel-default">
				<table id="vagas_minhas" class="table tablesaw" data-tablesaw-mode="columntoggle">
					<thead>
						<tr>
							<th data-tablesaw-sortable-col data-tablesaw-priority="persist">Cargo</th>
							<th data-tablesaw-sortable-col data-tablesaw-priority="2">Requisitos</th>
							<th data-tablesaw-sortable-col data-tablesaw-priority="1">Remuneração</th>
							<th data-tablesaw-sortable-col data-tablesaw-priority="3">Duração</th>
							<th data-tablesaw-sortable-col data-tablesaw-priority="persist">Inscreva-se</th>
						</tr>
					</thead>
					<tbody>
						<?php if(!is_null($view_vagas)){ foreach ($view_vagas as $key => $value) { echo $value;?>

						<?php }} ?>
					</tbody>
				</table>
				
			</div>
		</div>
	</div>
</div>