<div id="ret">	</div>
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-4">
			<h1>
				<span class="label label-info">
					Vagas em Aberto
				</span>
			</h1>
		</div>
		<div class="col-md-4 col-md-offset-1">
			<div class="input-group">
				<input type="text" id="busca" class="form-control" placeholder="Buscar...">
				<span class="input-group-btn">
					<button class="btn btn-default" type="button">Buscar</button>
				</span>
			</div><!-- /input-group -->
		</div>
		<div class="col-md-offset-2 col-xs-offset-1 col-md-8 col-xs-10">
			<div class="panel panel-default">
				<table class="table">
					<thead>
						<tr>
							<th>Cargo</th>
							<th>Requisitos</th>
							<th>Remuneração</th>
							<th>Duração</th>
							<th>Inscreva-se</th>
						</tr>
					</thead>
					<tbody>
						<?php if(!is_null($view_vagas)){ foreach ($view_vagas as $key => $value) { echo $value;?>

						<?php }} ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>