    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                   <h2> Pagina Inicial em Construção...</h2>
                </div>
                <div class="panel-body">
                    <?php 
                        $this->partial('message', array(
                            'msg' => 'Uhull! Você instalou e configurou o HXPHP Framework com sucesso!'
                        )); 
                    ?>
                    <p>
                        <a href="<?=BASE?>cadastro/cadastrousuario/">Cadastro</a>
                        <br>
                        <a href="<?=BASE?>login">Login</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
