<div class="container col-md-4 col-md-offset-4">
    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
    <div class="panel panel-default">
        <div class="panel-heading text-center">
            Login
        </div>
        <div class="panel-body">

            <form class="form-horizontal" action="<?=BASE?>login/logar/" method="POST">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" id="inputEmail3" name="email" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Senha</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="inputPassword3" name="senha" placeholder="Senha">
                    </div>
                </div>

                <div class="form-group btnbtn">
                            <button id="btn_cad" class="btn btn-success col-xs-12  col-md-6  pull-right">Logar</button>
                            <input type="button" class="btn btn-danger col-xs-12 col-md-6 pull-left" value="Voltar" onclick="location.href = '<?=BASE?>';">
                        </div>
                </div>

            </form>
        </div>
    </div>