	
</div>
	<div class="container col-md-12 col-xs-12 col-sm-12 col-lg-12">
		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center">
				GetStagio <?php echo date("Y"); ?> &copy; - Todos os direitos reservados
			</div>
		</div>
	</div>
</body>
</html>
<script type="text/javascript">
	$(".close").click(function(){
		$(".alert-block").hide();
	});
</script>

<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
<script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>