<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Bruno C. Santos">
    <meta name="generator" content="HXPHP Framework">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        <?php echo $view_title; ?>
    </title>
    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon.jpg" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
    <?php 
		echo $add_css;
	?>
</head>

<body id="bootstrap-overrides">
    <?php 
          echo (isset($this->menuget) ? $this->menuget->getMenu() : "
            <div id='fundo-externo'>
                <div id='fundo'>
                </div>
            </div>
            <nav class='navbar navbar-default bgmenu container-fluid'>
                <div class='col-xs-offset-3 col-xs-6 col-sm-offset-4 col-sm-4 col-md-offset-5 col-md-2'>
                    <a href='' class='navbabrand'>
                        <img id='gtlogo' class='img-responsive' src='".IMG."gt.png' alt=''>
                    </a>
                </div>
            </nav>"
            ); 
        ?>