<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Bruno C. Santos">
    <meta name="generator" content="HXPHP Framework">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        <?php echo $view_title; ?>
    </title>
    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon.jpg" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
    <?php 
		echo $add_css;
		echo $add_js;
	?>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid col-md-4 col-md-offset-4">
                <a href="#" class="navbar-brand centro col-sm-12 col-md-12 col-lg-12">
                    GetStagio
                </a>
        </div>
    </nav>
    <div class="menu">
        <?php echo (isset($this->menu) ? $this->menu : ""); ?>
    </div>